spring:
  datasource:
    tomcat:
      max-active: 50
      max-idle: 10
      max-wait: 1000
      test-on-borrow: true
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: 27017
      database: amazon-test
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
      properties:
        client.transport.ignore_cluster_name: true


server:
  port: ${SERVER_PORT:8080}
  servlet:
    application-display-name: amazon-test

logging:
  level:
    com:
      gleb: DEBUG