version: '3.0'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - transport.host=0.0.0.0
      - http.host=0.0.0.0
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - amazontest
  mongo:
    image: mongo:3.4-jessie
    ports:
      - 27017:27017
    networks:
      - amazontest
  amazon-test-app:
    image: gerasimenko/amazon-test:latest
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - elasticsearch
    environment:
      - MONGO_HOST=mongo
      - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
      - SPRING_DATA_ELASTICSEARCH_REPOSITORIES_ENABLED=true
      - SPRING_DATA_ELASTICSEARCH_CLUSTER_NAME=elasticsearch
    networks:
      - amazontest

networks:
  amazontest:
    driver: bridge